/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Principal;

import javax.swing.ImageIcon;
import logica.CallBack;
import logica.MetodosUtiles;
import vista.ClinicaDental_GUI;
import vista.ClinicaDental_LogIn;

/**
 *
 * @author IVÁN-PC
 */
public class Principal_GUI extends javax.swing.JPanel implements CallBack, MetodosUtiles{

    /**
     * Creates new form Principal_GUI
     */
    private ClinicaDental_GUI jFramePrincipal;
    
    
    public Principal_GUI() {
        initComponents();
        rellenarMenuPrinicipal();
    }
    
    public void mostrar(ClinicaDental_GUI jFramePrincipal){
        setVisible(true);
        this.jFramePrincipal = jFramePrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCabecera = new javax.swing.JLabel();
        labSalir = new javax.swing.JLabel();
        butNotasRapidas = new javax.swing.JButton();
        butCerrarSesion = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();
        labNotasRapidas = new javax.swing.JLabel();
        labCerrarSesion = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(785, 530));
        setMinimumSize(new java.awt.Dimension(785, 530));

        labCabecera.setBackground(new java.awt.Color(255, 153, 51));
        labCabecera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCabecera.setText("PRINCIPAL");
        labCabecera.setOpaque(true);

        labSalir.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        labSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSalir.setText("gf");

        butNotasRapidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFuncionalesActionPerformed(evt);
            }
        });

        butCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFuncionalesActionPerformed(evt);
            }
        });

        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFuncionalesActionPerformed(evt);
            }
        });

        labNotasRapidas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        labNotasRapidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNotasRapidas.setText("fg");

        labCerrarSesion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        labCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCerrarSesion.setText("fg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(butNotasRapidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labNotasRapidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(144, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(butCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butNotasRapidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labNotasRapidas)
                        .addComponent(labCerrarSesion)
                        .addComponent(labSalir))
                    .addContainerGap(180, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rellenarMenuPrinicipal() {
        labNotasRapidas.setText("NOTAS RÁPIDAS");
        butNotasRapidas.setIcon(new ImageIcon(getClass().getResource("/img/iconsButtons/notasRapidas.png")));
        labCerrarSesion.setText("CERRAR SESIÓN");
        butCerrarSesion.setIcon(new ImageIcon(getClass().getResource("/img/iconsButtons/cerrarSesion.png")));
        labSalir.setText("SALIR");
        butSalir.setIcon(new ImageIcon(getClass().getResource("/img/iconsButtons/salir.png")));
    }
    
    private void ocultarFuncionalidades(){
        labCabecera.setVisible(false);
        labNotasRapidas.setVisible(false);
        butNotasRapidas.setVisible(false);
        labCerrarSesion.setVisible(false);
        butCerrarSesion.setVisible(false);
        labSalir.setVisible(false);
        butSalir.setVisible(false);
    }
    
    private void mostrarFuncionalidades(){
        labCabecera.setVisible(true);
        labNotasRapidas.setVisible(true);
        butNotasRapidas.setVisible(true);
        labCerrarSesion.setVisible(true);
        butCerrarSesion.setVisible(true);
        labSalir.setVisible(true);
        butSalir.setVisible(true);
    }
    
    
    private void butFuncionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFuncionalesActionPerformed

        if (evt.getSource() == butNotasRapidas) {
            ocultarFuncionalidades();
            jFramePrincipal.getMenuBarClinica().setVisible(false);
            NotasRapidas_GUI panelNotasRapidas = new NotasRapidas_GUI(this);
            panelNotasRapidas.setSize(785, 530);
            panelNotasRapidas.setVisible(false);
            this.add(panelNotasRapidas);
            panelNotasRapidas.mostrar();
        } else if (evt.getSource() == butCerrarSesion) {
            try {
                if (salirYCerrarConexion(jFramePrincipal)) {
                    ClinicaDental_GUI.getHiloReloj().stop();
                    ClinicaDental_LogIn cliLogin = new ClinicaDental_LogIn();
                    cliLogin.setVisible(false);
                    cliLogin.setSize(500, 500);
                    cliLogin.setVisible(true);
                }
            } catch (Exception ex) {
            }
        } else if (evt.getSource() == butSalir) {
            try {
                if(salirYCerrarConexion(jFramePrincipal)){
                    ClinicaDental_GUI.getHiloReloj().stop();
                }
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_butFuncionalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCerrarSesion;
    private javax.swing.JButton butNotasRapidas;
    private javax.swing.JButton butSalir;
    private javax.swing.JLabel labCabecera;
    private javax.swing.JLabel labCerrarSesion;
    private javax.swing.JLabel labNotasRapidas;
    private javax.swing.JLabel labSalir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void panelDeLlamada() {
        setVisible(true);
        jFramePrincipal.getMenuBarClinica().setVisible(true);
        mostrarFuncionalidades();
    }
}
