/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import logica.CallBack;
import logica.ConexionBD;
import logica.HiloReloj;
import logica.MetodosUtiles;
import vista.Citas.Citas_GUI;
import vista.Clientes.Clientes_GUI;
import vista.Doctores.Doctores_GUI;
import vista.Principal.Principal_GUI;
import vista.Servicios.Servicios_GUI;

/**
 *
 * @author IVÁN-PC
 */
public class ClinicaDental_GUI extends javax.swing.JFrame implements MetodosUtiles,CallBack {

    private static HiloReloj hiloReloj;
    
    private Principal_GUI panelPrincipal;
    private Doctores_GUI panelDoctores;
    private Servicios_GUI panelServicios;
    private Clientes_GUI panelClientes;
    private Citas_GUI panelCitas;

    public ClinicaDental_GUI() {
        initComponents();
    }

    public JMenuBar getMenuBarClinica() {
        return menuBarClinica;
    }

    public static HiloReloj getHiloReloj() {
        return hiloReloj;
    }

    public static void setHiloReloj(HiloReloj hiloReloj) {
        ClinicaDental_GUI.hiloReloj = hiloReloj;
    }

    public JLabel getLabSuspesion() {
        return labSuspesion;
    }

    public void mostrar() throws SQLException {
        setVisible(true);
        labNombreUsuario.setText(ConexionBD.getConn().getMetaData().getUserName());
        hiloReloj = new HiloReloj(labFechaSistema);
        menuPrincipal.setSelected(true);
        abrirMenuPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labSuspesion = new javax.swing.JLabel();
        labNombreUsuario = new javax.swing.JLabel();
        labFechaSistema = new javax.swing.JLabel();
        menuBarClinica = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuDoctores = new javax.swing.JMenu();
        menuServicios = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuCitas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BestCliDent-Menú");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("BestCliDent-Menú"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labSuspesion.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        labNombreUsuario.setBackground(new java.awt.Color(51, 255, 204));
        labNombreUsuario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNombreUsuario.setOpaque(true);

        labFechaSistema.setBackground(new java.awt.Color(0, 255, 204));
        labFechaSistema.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labFechaSistema.setForeground(new java.awt.Color(0, 0, 0));
        labFechaSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFechaSistema.setOpaque(true);

        menuPrincipal.setText("Principal");
        menuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBarClinicaMouseEntered(evt);
            }
        });
        menuBarClinica.add(menuPrincipal);

        menuDoctores.setText("Doctores");
        menuDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBarClinicaMouseEntered(evt);
            }
        });
        menuBarClinica.add(menuDoctores);

        menuServicios.setText("Servicios");
        menuServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBarClinicaMouseEntered(evt);
            }
        });
        menuBarClinica.add(menuServicios);

        menuClientes.setText("Clientes");
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBarClinicaMouseEntered(evt);
            }
        });
        menuBarClinica.add(menuClientes);

        menuCitas.setText("Citas");
        menuCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBarClinicaMouseEntered(evt);
            }
        });
        menuBarClinica.add(menuCitas);

        setJMenuBar(menuBarClinica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labFechaSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSuspesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(labSuspesion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFechaSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarPanelMostrado() {
        if (menuPrincipal.isSelected()) {
            panelPrincipal.setVisible(false);
            panelPrincipal.removeAll();
            this.remove(panelPrincipal);
        } else if (menuDoctores.isSelected()) {
            panelDoctores.setVisible(false);
            panelDoctores.removeAll();
            this.remove(panelDoctores);
        } else if (menuServicios.isSelected()) {
            panelServicios.setVisible(false);
            panelServicios.removeAll();
            this.remove(panelServicios);
        }else if (menuClientes.isSelected()) {
            panelClientes.setVisible(false);
            panelClientes.removeAll();
            this.remove(panelClientes);
        }else if (menuCitas.isSelected()) {
            panelCitas.setVisible(false);
            panelCitas.removeAll();
            this.remove(panelCitas);
        }
    }

    private void abrirMenuPrincipal() {
        menuPrincipal.setSelected(true);
        panelPrincipal = new Principal_GUI();
        panelPrincipal.setVisible(false);
        panelPrincipal.setSize(785, 530);
        this.add(panelPrincipal);
        panelPrincipal.mostrar(this);
    }

    private void menuBarClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarClinicaMouseEntered

        JMenu jMenuTMP = (JMenu) evt.getComponent();
        cerrarPanelMostrado();
        menuPrincipal.setSelected(false);
        menuDoctores.setSelected(false);
        menuServicios.setSelected(false);
        menuClientes.setSelected(false);
        menuCitas.setSelected(false);

        if (jMenuTMP == menuPrincipal) {
            abrirMenuPrincipal();
        } else if (jMenuTMP == menuDoctores) {
            menuDoctores.setSelected(true);
            panelDoctores = new Doctores_GUI();
            panelDoctores.setVisible(false);
            panelDoctores.setSize(785, 530);
            this.add(panelDoctores);
            panelDoctores.mostrar();
        } else if (jMenuTMP == menuServicios) {
            menuServicios.setSelected(true);
            panelServicios = new Servicios_GUI();
            panelServicios.setVisible(false);
            panelServicios.setSize(785, 530);
            this.add(panelServicios);
            panelServicios.mostrar();
        } else if (jMenuTMP == menuClientes) {
            menuClientes.setSelected(true);
            panelClientes = new Clientes_GUI();
            panelClientes.setVisible(false);
            panelClientes.setSize(785, 530);
            this.add(panelClientes);
            panelClientes.mostrar();
        } else if (jMenuTMP == menuCitas) {
            menuCitas.setSelected(true);
            panelCitas = new Citas_GUI();
            panelCitas.setVisible(false);
            panelCitas.setSize(785,530);
            this.add(panelCitas);
            panelCitas.mostrar();
        }
    }//GEN-LAST:event_menuBarClinicaMouseEntered


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (salirYCerrarConexion(this)) {
            this.hiloReloj.stop();
        }
    }//GEN-LAST:event_formWindowClosing

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicaDental_GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicaDental_GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicaDental_GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicaDental_GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicaDental_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labFechaSistema;
    private javax.swing.JLabel labNombreUsuario;
    private javax.swing.JLabel labSuspesion;
    private javax.swing.JMenuBar menuBarClinica;
    private javax.swing.JMenu menuCitas;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuDoctores;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuServicios;
    // End of variables declaration//GEN-END:variables

}
