/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.ComponentOrientation;
import java.awt.Cursor;
import java.awt.GridBagLayout;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import logica.CallBack;
import logica.ConexionBD;
import logica.HiloReloj;
import logica.MetodosUtiles;
import vista.Citas.Citas_GUI;
import vista.Clientes.Clientes_GUI;
import vista.Doctores.Doctores_GUI;
import vista.Principal.Principal_GUI;
import vista.Servicios.Servicios_GUI;

/**
 *
 * @author IVÁN-PC
 */
public class ClinicaDental_GUI extends javax.swing.JFrame implements MetodosUtiles, CallBack {

    private static HiloReloj hiloReloj;

    private Principal_GUI panelPrincipal;
    private Doctores_GUI panelDoctores;
    private Servicios_GUI panelServicios;
    private Clientes_GUI panelClientes;
    private Citas_GUI panelCitas;

    private JPanel panelSeleccionado;

    public ClinicaDental_GUI() {
        initComponents();
    }

    public JMenuBar getMenuBarClinica() {
        return menuBarClinica;
    }

    public static HiloReloj getHiloReloj() {
        return hiloReloj;
    }

    public static void setHiloReloj(HiloReloj hiloReloj) {
        ClinicaDental_GUI.hiloReloj = hiloReloj;
    }

    public JLabel getLabSuspesion() {
        return labSuspesion;
    }

    public void mostrar() throws SQLException {
        setVisible(true);
        labNombreUsuario.setText(ConexionBD.getConn().getMetaData().getUserName());
        hiloReloj = new HiloReloj(labFechaSistema);
        abrirMenuPrincipal();

        //Para orientar el JMenu al centro y la imagen de derecha a izquierda.
        menuBarClinica.setLayout(new GridBagLayout());
        menuClinica.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labSuspesion = new javax.swing.JLabel();
        labNombreUsuario = new javax.swing.JLabel();
        labFechaSistema = new javax.swing.JLabel();
        menuBarClinica = new javax.swing.JMenuBar();
        menuClinica = new javax.swing.JMenu();
        menuItemPrincipal = new javax.swing.JMenuItem();
        menuItemDoctores = new javax.swing.JMenuItem();
        menuItemServicios = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemCitas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BestCliDent-Menú");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("BestCliDent-Menú"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labSuspesion.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        labNombreUsuario.setBackground(new java.awt.Color(51, 255, 204));
        labNombreUsuario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNombreUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labNombreUsuario.setOpaque(true);

        labFechaSistema.setBackground(new java.awt.Color(0, 255, 204));
        labFechaSistema.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labFechaSistema.setForeground(new java.awt.Color(0, 0, 0));
        labFechaSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFechaSistema.setOpaque(true);

        menuClinica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsButtons/iconoDesplegable.png"))); // NOI18N
        menuClinica.setText("MENÚ DESPLEGABLE");
        menuClinica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuClinicaMouseEntered(evt);
            }
        });

        menuItemPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuItemPrincipal.setText("Principal");
        menuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClinicaActionPerformed(evt);
            }
        });
        menuClinica.add(menuItemPrincipal);

        menuItemDoctores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuItemDoctores.setText("Doctores");
        menuItemDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClinicaActionPerformed(evt);
            }
        });
        menuClinica.add(menuItemDoctores);

        menuItemServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemServicios.setText("Servicios");
        menuItemServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClinicaActionPerformed(evt);
            }
        });
        menuClinica.add(menuItemServicios);

        menuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClinicaActionPerformed(evt);
            }
        });
        menuClinica.add(menuItemClientes);

        menuItemCitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK));
        menuItemCitas.setText("Citas");
        menuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClinicaActionPerformed(evt);
            }
        });
        menuClinica.add(menuItemCitas);

        menuBarClinica.add(menuClinica);

        setJMenuBar(menuBarClinica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labFechaSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSuspesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(527, Short.MAX_VALUE)
                .addComponent(labSuspesion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labFechaSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Cierra el panel actual que se está mostrando
    private void cerrarPanelMostrado() {

        panelSeleccionado.setVisible(false);
        panelSeleccionado.removeAll();
        this.remove(panelSeleccionado);
    }

    //Abre el menú principal, separado en un método para evitar duplicar código,
    //ya que se inicia al abrir el frame
    private void abrirMenuPrincipal() {
        panelPrincipal = new Principal_GUI();
        panelPrincipal.setVisible(false);
        panelPrincipal.setSize(785, 530);
        this.add(panelPrincipal);
        panelSeleccionado = panelPrincipal;
        panelPrincipal.mostrar(this);
    }


    //Cierra la conexión de la bbdd y detiene el hilo del reloj
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (salirYCerrarConexion(this)) {
            hiloReloj.stop();
        }
    }//GEN-LAST:event_formWindowClosing

    //Funcionalidades del menú para ocultar y cerrar paneles
    private void menuClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClinicaActionPerformed
        cerrarPanelMostrado();

        if (evt.getSource() == menuItemPrincipal) {
            abrirMenuPrincipal();
        } else if (evt.getSource() == menuItemDoctores) {
            panelDoctores = new Doctores_GUI();
            panelDoctores.setVisible(false);
            panelDoctores.setSize(785, 530);
            this.add(panelDoctores);
            panelSeleccionado = panelDoctores;
            panelDoctores.mostrar();
        } else if (evt.getSource() == menuItemServicios) {
            panelServicios = new Servicios_GUI();
            panelServicios.setVisible(false);
            panelServicios.setSize(785, 530);
            this.add(panelServicios);
            panelSeleccionado = panelServicios;
            panelServicios.mostrar();
        } else if (evt.getSource() == menuItemClientes) {
            panelClientes = new Clientes_GUI();
            panelClientes.setVisible(false);
            panelClientes.setSize(785, 530);
            this.add(panelClientes);
            panelSeleccionado = panelClientes;
            panelClientes.mostrar();
        } else if (evt.getSource() == menuItemCitas) {
            panelCitas = new Citas_GUI();
            panelCitas.setVisible(false);
            panelCitas.setSize(785, 530);
            this.add(panelCitas);
            panelSeleccionado = panelCitas;
            panelCitas.mostrar();
        }
    }//GEN-LAST:event_menuClinicaActionPerformed

    //Cambiar el cursor al pasar por encima del menuDesplegable
    private void menuClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClinicaMouseEntered
        
        ((JMenu) evt.getSource()).setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuClinicaMouseEntered

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labFechaSistema;
    private javax.swing.JLabel labNombreUsuario;
    private javax.swing.JLabel labSuspesion;
    private javax.swing.JMenuBar menuBarClinica;
    private javax.swing.JMenu menuClinica;
    private javax.swing.JMenuItem menuItemCitas;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemDoctores;
    private javax.swing.JMenuItem menuItemPrincipal;
    private javax.swing.JMenuItem menuItemServicios;
    // End of variables declaration//GEN-END:variables

}
